// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgzK0eaRRE0hTM3kcnhnZ2ly6HuA48Ls',
    appId: '1:185267669548:web:f30342e6d65c619e4ddf89',
    messagingSenderId: '185267669548',
    projectId: 'eval2-3ea6f',
    authDomain: 'eval2-3ea6f.firebaseapp.com',
    storageBucket: 'eval2-3ea6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0Cnk8ZKE2-2X1MFWQARQLgd1KYdjODo',
    appId: '1:185267669548:android:f5efff827a1b4d9f4ddf89',
    messagingSenderId: '185267669548',
    projectId: 'eval2-3ea6f',
    storageBucket: 'eval2-3ea6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Oy-rTjQBBP8sJbnZ2ZU08z_-HkGe_Vk',
    appId: '1:185267669548:ios:e23d664e40ad3a324ddf89',
    messagingSenderId: '185267669548',
    projectId: 'eval2-3ea6f',
    storageBucket: 'eval2-3ea6f.appspot.com',
    iosBundleId: 'com.katiaclimaco.evals2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Oy-rTjQBBP8sJbnZ2ZU08z_-HkGe_Vk',
    appId: '1:185267669548:ios:a0933792e8a8a83c4ddf89',
    messagingSenderId: '185267669548',
    projectId: 'eval2-3ea6f',
    storageBucket: 'eval2-3ea6f.appspot.com',
    iosBundleId: 'com.katiaclimaco.evals2.RunnerTests',
  );
}
